### ISSUE TITLE
Timezones

### ISSUE THREAD

**Issue by g-martin772** [Team-MPM/MPM-Smart#44]
- [x] Support all Timezones as Config Options
- [x] Support non-integer UTC offsets
- [x] Make sure time shifts are handled correctly

**Comment by NotSayo** [comment]
Check commit bc0fad47 on #43

**Comment by g-martin772** [comment]
Hehehe, don’t just close my issues, get this over to 44-timezones and open a pr, when merged it will be marked as completed automatically!

**Comment by g-martin772** [comment]
We’ll just forget about it
